### ISSUE TITLE
Compatibilidade com PHP 7.4

### ISSUE THREAD

**Issue by mrprompt** [vsilva472/phpcpf#1]

**Comment by vsilva472** [comment]
Poderia descrever o qual seria essa compatibilidade? A princípio todos os testes passaram nas versões do php 7.1 até 7.4 no [Travis](https://travis-ci.org/vsilva472/phpcpf) será que esqueci algo?

**Comment by mrprompt** [comment]
Vou fechar a issue pq acabei de descobrir que é comportamento do Laravel (usando a outra lib) que tá passando um objeto como parâmetro, e não um array, aí o PHP 7.4 informa que a referência a um objeto usando a noteção de array é inválida...
